default: &default
  adapter: postgresql
  encoding: unicode
  username: bhawesh
  password: bhawesh
  host: localhost
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: food_reserve_development

test:
  <<: *default
  database: food_reserve_test

production:
  <<: *default
  database: food_reserve_production
  username: bhawesh
  password: <%= ENV["FOOD_RESERVE_DATABASE_PASSWORD"] %>
